let musics = {
    "musics" : [
        {
            "num": 1,
            "song": "Insecure(feat. Pink Sweat$)",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 182,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=hlZpDbi56Qc&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=2",
        },
        {
            "num": 2,
            "song": "IDGAF",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 169,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=hlZpDbi56Qc&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=3",
        },
        {
            "num": 3,
            "song": "Fiji Fine",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 181,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=hlZpDbi56Qc&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=4",
        },
        {
            "num": 4,
            "song": "Lil Rich(feat. Mae Muller)",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 169,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=hlZpDbi56Qc&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=5",
        },
        {
            "num": 5,
            "song": "Multiply",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 246,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=hlZpDbi56Qc&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=6",
        },
        {
            "num": 6,
            "song": "Mrs. Jons",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 199,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=hlZpDbi56Qc&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=7",
        },
        {
            "num": 7,
            "song": "Freezing",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 178,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=hlZpDbi56Qc&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=8",
        },
        {
            "num": 8,
            "song": "Sweet(feat. Landon Sears)",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 227,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=hlZpDbi56Qc&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=9",
        },
        {
            "num": 9,
            "song": "Twenties",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 256,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=hlZpDbi56Qc&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=10",
        },
        {
            "num": 10,
            "song": "When Martin Died",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 107,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=ipiNLO6-WrM&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=11",
        },
        {
            "num": 11,
            "song": "Drag Race",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 269,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=hlZpDbi56Qc&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=12",
        },
        {
            "num": 12,
            "song": "Scottie Pippen",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 193,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=hlZpDbi56Qc&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=13",
        },
        {
            "num": 13,
            "song": "Upper East Side",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 197,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=hlZpDbi56Qc&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=14",
        },
        {
            "num": 14,
            "song": "Pocket",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 219,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=hlZpDbi56Qc&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=15",
        },
        {
            "num": 15,
            "song": "Henny in the Hamptons",
            "artist": "Bren Joy",
            "album": "Twenties (Deluxe)",
            "release": "2020.03.06",
            "playtime": 198,
            "genre": "R&B",
            "cover": "https://image.bugsm.co.kr/album/images/500/9854/985425.jpg",
            "url": "https://www.youtube.com/watch?v=hlZpDbi56Qc&list=PLko9B37V-MRH8nUKACy_Rp2Imzo5bheaX&index=16",
        },
        {
            "num": 1,
            "song": "Crescent Moon",
            "artist": "Conor Albert, James Smith",
            "album": "Crescent Moon",
            "release": "2021.11.11",
            "playtime": 200,
            "genre": "R&B",
            "cover": "https://imagescdn.junodownload.com/300/CS5336022-02A-MED.jpg",
            "url": "https://youtu.be/YVPAs42vgfE",
        },
        {
            "num": 1,
            "song": "At My Worst",
            "artist": "Pink Sweat$",
            "album": "At My Worst",
            "release": "2021.1.27",
            "playtime": 170,
            "genre": "R&B",
            "cover": "https://s.mxmcdn.net/images-storage/albums4/8/9/5/6/1/5/52516598_800_800.jpg",
            "url": "https://youtu.be/R176lnVtwyg",
        },
        {
            "num": 1,
            "song": "At My Worst",
            "artist": "Pink Sweat$",
            "album": "At My Worst2",
            "release": "2021.1.27",
            "playtime": 170,
            "genre": "R&B",
            "cover": "https://s.mxmcdn.net/images-storage/albums4/8/9/5/6/1/5/52516598_800_800.jpg",
            "url": "https://youtu.be/R176lnVtwyg",
        },
        {
            "num": 1,
            "song": "At My Worst",
            "artist": "Pink Sweat$",
            "album": "At My Worst3",
            "release": "2021.1.27",
            "playtime": 170,
            "genre": "R&B",
            "cover": "https://s.mxmcdn.net/images-storage/albums4/8/9/5/6/1/5/52516598_800_800.jpg",
            "url": "https://youtu.be/R176lnVtwyg",
        },
        {
            "num": 1,
            "song": "At My Worst",
            "artist": "Pink Sweat$",
            "album": "At My Worst4",
            "release": "2021.1.27",
            "playtime": 170,
            "genre": "R&B",
            "cover": "https://s.mxmcdn.net/images-storage/albums4/8/9/5/6/1/5/52516598_800_800.jpg",
            "url": "https://youtu.be/R176lnVtwyg",
        },
        {
            "num": 1,
            "song": "At My Worst",
            "artist": "Pink Sweat$",
            "album": "At My Worst5",
            "release": "2021.1.27",
            "playtime": 170,
            "genre": "R&B",
            "cover": "https://s.mxmcdn.net/images-storage/albums4/8/9/5/6/1/5/52516598_800_800.jpg",
            "url": "https://youtu.be/R176lnVtwyg",
        },
        {
            "num": 1,
            "song": "At My Worst",
            "artist": "Pink Sweat$",
            "album": "At My Worst6",
            "release": "2021.1.27",
            "playtime": 170,
            "genre": "R&B",
            "cover": "https://s.mxmcdn.net/images-storage/albums4/8/9/5/6/1/5/52516598_800_800.jpg",
            "url": "https://youtu.be/R176lnVtwyg",
        },
    ]
}

export function getMusics() {
    return musics;
};

export function getAlbum(album) {
    return musics["musics"].find(
        music => music.album === album
    );
}